package model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Attempt generated by hbm2java
 */
public class Attempt implements java.io.Serializable {

    private static final long serialVersionUID = -3938298750519059006L;

    private int id;
    private Account examinee;
    private Test test;
    private Date startTime;
    private Date endTime;
    private double score;
    private Set<Choice> choices = new HashSet<>(0);

    public Attempt() {
    }

    public Attempt(int id, Date startTime, Date endTime, double score) {
        this.id = id;
        this.startTime = startTime;
        this.endTime = endTime;
        this.score = score;
    }

    public Attempt(int id, Account examinee, Test test, Date startTime, Date endTime, double score, Set<Choice> choices) {
        this.id = id;
        this.examinee = examinee;
        this.test = test;
        this.startTime = startTime;
        this.endTime = endTime;
        this.score = score;
        this.choices = choices;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Account getExaminee() {
        return this.examinee;
    }

    public void setExaminee(Account examinee) {
        this.examinee = examinee;
    }

    public Test getTest() {
        return this.test;
    }

    public void setTest(Test test) {
        this.test = test;
    }

    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public double getScore() {
        return this.score;
    }

    public void setScore(double score) {
        this.score = score;
    }

    public Set<Choice> getChoices() {
        return this.choices;
    }

    public void setChoices(Set<Choice> choices) {
        this.choices = choices;
    }

}
