package model;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

    private static final long serialVersionUID = 537688796671496513L;

    private String id;
    private String name;

    public Course() {
    }

    public Course(String id, String name) {
        this.id = id;
        this.name = name;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
