package model;

import java.util.HashSet;
import java.util.Set;

/**
 * Question generated by hbm2java
 */
public class Question implements java.io.Serializable {

    private static final long serialVersionUID = -1507712911226653478L;

    private int id;
    private Account owner;
    private Course course;
    private String content;
    private Set<Choice> choices = new HashSet<>(0);

    public Question() {
    }

    public Question(int id, String content) {
        this.id = id;
        this.content = content;
    }

    public Question(int id, Account owner, Course course, String content, Set<Choice> choices) {
        this.id = id;
        this.owner = owner;
        this.course = course;
        this.content = content;
        this.choices = choices;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Account getOwner() {
        return this.owner;
    }

    public void setOwner(Account owner) {
        this.owner = owner;
    }

    public Course getCourse() {
        return this.course;
    }

    public void setCourse(Course course) {
        this.course = course;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Set<Choice> getChoices() {
        return this.choices;
    }

    public void setChoices(Set<Choice> choices) {
        this.choices = choices;
    }

}
